import React, { useState } from 'react';
import { useStartupStore } from '../store/startupStore';
import { useAuthStore } from '../store/authStore';
import { apiRequest } from '../utils/api';
import { RefreshCw, FileText, Download, ChevronLeft, ChevronRight, Printer } from 'lucide-react';

interface Slide {
  slideNumber: number;
  title: string;
  content: string;
  bulletPoints: string[];
}

export const PitchDeckGenerator: React.FC = () => {
  const { setCredits } = useAuthStore();
  const { activeStartup, activeModules, setActiveModules } = useStartupStore();

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [currentSlideIdx, setCurrentSlideIdx] = useState(0);

  const deckData = activeModules?.pitchDeck;
  const slides: Slide[] = deckData?.slides || [];

  const handleGenerate = async () => {
    if (!activeStartup) return;
    setLoading(true);
    setError(null);

    try {
      const res = await apiRequest('/ai/pitch-deck', {
        method: 'POST',
        body: { startupId: activeStartup._id },
      });

      if (res.success) {
        if (res.userCredits !== undefined) {
          setCredits(res.userCredits);
        }
        setActiveModules({
          ...activeModules,
          pitchDeck: res.pitchDeck,
        });
        setCurrentSlideIdx(0);
      }
    } catch (err: any) {
      setError(err.message || 'Generation failed.');
    } finally {
      setLoading(false);
    }
  };

  const handleExportText = () => {
    if (slides.length === 0) return;
    
    let content = `PITCH DECK OUTLINE - ${activeStartup?.name?.toUpperCase()}\n`;
    content += `Generated by FoundrAI Co-Founder Platform\n`;
    content += `==========================================\n\n`;

    slides.forEach((s) => {
      content += `SLIDE ${s.slideNumber}: ${s.title.toUpperCase()}\n`;
      content += `------------------------------------------\n`;
      content += `${s.content}\n\n`;
      s.bulletPoints.forEach((pt) => {
        content += `• ${pt}\n`;
      });
      content += `\n\n`;
    });

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `${activeStartup?.name?.replace(/\s+/g, '_')}_pitch_deck_structure.txt`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Direct print layouts for PDF export
  const handlePrintExport = () => {
    window.print();
  };

  const activeSlide = slides[currentSlideIdx];

  return (
    <div className="max-w-4xl mx-auto space-y-8 fade-in select-none">
      {/* Print-Only Style Sheet */}
      <style>{`
        @media print {
          body * {
            visibility: hidden;
            background-color: #ffffff !important;
            color: #000000 !important;
          }
          #print-area, #print-area * {
            visibility: visible;
          }
          #print-area {
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
          }
          .slide-page {
            page-break-after: always;
            border: 2px solid #222222 !important;
            padding: 40px !important;
            margin-bottom: 20px !important;
            background: #ffffff !important;
            color: #000000 !important;
          }
          .print-title {
            color: #D4AF37 !important;
          }
        }
      `}</style>

      {/* Header */}
      <div className="flex justify-between items-center border-b border-dark-border pb-4 print:hidden">
        <div>
          <h1 className="text-xl font-bold tracking-tight text-white flex items-center gap-2">
            <FileText className="h-5 w-5 text-gold" />
            Pitch Deck Generator
          </h1>
          <p className="text-xs text-gray-500 mt-1">
            Build YC-grade, 10-slide presentation scripts with structured messaging blocks.
          </p>
        </div>
        
        {activeStartup && !loading && slides.length > 0 && (
          <div className="flex items-center gap-3">
            <button
              onClick={handlePrintExport}
              className="flex items-center gap-1.5 rounded-custom border border-dark-border hover:border-gold/50 bg-dark-card hover:bg-dark-border text-white text-xs px-3.5 py-2 transition-colors cursor-pointer"
            >
              <Printer className="h-3.5 w-3.5 text-gold" /> Export PDF (Print)
            </button>
            <button
              onClick={handleExportText}
              className="flex items-center gap-1.5 rounded-custom border border-dark-border hover:border-gold/50 bg-dark-card hover:bg-dark-border text-white text-xs px-3.5 py-2 transition-colors cursor-pointer"
            >
              <Download className="h-3.5 w-3.5 text-gold" /> Export PPTX Structure
            </button>
            <button
              onClick={handleGenerate}
              className="flex items-center gap-1.5 rounded-custom border border-dark-border hover:border-gold/50 bg-dark-card hover:bg-dark-border text-gray-400 hover:text-white text-xs px-3.5 py-2 transition-colors cursor-pointer"
            >
              <RefreshCw className="h-3.5 w-3.5" /> Rebuild Deck
            </button>
          </div>
        )}

        {activeStartup && slides.length === 0 && (
          <button
            onClick={handleGenerate}
            disabled={loading}
            className="flex items-center gap-2 rounded-custom bg-gold hover:bg-gold-hover disabled:bg-dark-border text-black disabled:text-gray-500 font-semibold text-xs px-4 py-2 transition-colors cursor-pointer"
          >
            {loading ? <RefreshCw className="h-3.5 w-3.5 animate-spin" /> : 'Generate Pitch Slides'}
          </button>
        )}
      </div>

      {error && (
        <div className="rounded-md border border-red-900 bg-red-950/10 px-4 py-3 text-xs text-red-400 print:hidden">
          {error}
        </div>
      )}

      {/* Landing / Mock Empty State */}
      {slides.length === 0 && !loading && (
        <div className="rounded-custom border border-dark-border bg-dark-card p-12 text-center print:hidden">
          <FileText className="h-10 w-10 text-gold/40 mx-auto mb-4" />
          <h3 className="text-sm font-semibold text-white mb-2">No Pitch Deck Generated</h3>
          <p className="text-xs text-gray-500 max-w-sm mx-auto mb-6">
            Create standard investor presentation slide texts customized for **{activeStartup?.name}**.
          </p>
          <button
            onClick={handleGenerate}
            className="rounded-custom bg-gold hover:bg-gold-hover text-black font-semibold text-xs px-5 py-2.5 transition-colors cursor-pointer"
          >
            Run Pitch Deck Builder (Uses 1 Credit)
          </button>
        </div>
      )}

      {loading && (
        <div className="rounded-custom border border-dark-border bg-dark-card p-20 text-center print:hidden">
          <RefreshCw className="h-10 w-10 text-gold animate-spin mx-auto mb-4" />
          <h3 className="text-sm font-semibold text-white mb-2">Assembling Presentation Material</h3>
          <p className="text-xs text-gray-500 max-w-xs mx-auto">
            Constructing Problem definitions, mapping Product values, and writing Go-To-Market strategies...
          </p>
        </div>
      )}

      {/* Slide Viewer (Interactive presentation carousel) */}
      {slides.length > 0 && !loading && (
        <div className="space-y-6 print:hidden">
          {/* Deck Navigator */}
          <div className="flex items-center justify-between">
            <span className="text-[10px] text-gray-500 font-mono">
              SLIDE {activeSlide.slideNumber} OF {slides.length}
            </span>
            <div className="flex gap-2">
              <button
                disabled={currentSlideIdx === 0}
                onClick={() => setCurrentSlideIdx((p) => p - 1)}
                className="p-2 rounded-custom border border-dark-border hover:border-gold/50 bg-dark-card text-gray-400 hover:text-white disabled:opacity-30 disabled:border-dark-border transition-all cursor-pointer"
              >
                <ChevronLeft className="h-4 w-4" />
              </button>
              <button
                disabled={currentSlideIdx === slides.length - 1}
                onClick={() => setCurrentSlideIdx((p) => p + 1)}
                className="p-2 rounded-custom border border-dark-border hover:border-gold/50 bg-dark-card text-gray-400 hover:text-white disabled:opacity-30 disabled:border-dark-border transition-all cursor-pointer"
              >
                <ChevronRight className="h-4 w-4" />
              </button>
            </div>
          </div>

          {/* Active Slide Display */}
          <div className="rounded-custom border border-dark-border bg-dark-card p-8 md:p-12 min-h-80 flex flex-col justify-between shadow-2xl relative overflow-hidden">
            {/* Header info */}
            <div>
              <div className="text-[9px] text-gold/60 tracking-wider uppercase font-mono mb-2">
                Slide {activeSlide.slideNumber} — {activeSlide.title}
              </div>
              <h2 className="text-xl md:text-2xl font-bold tracking-tight text-white mb-4 border-b border-dark-border pb-3">
                {activeSlide.title}
              </h2>
              <p className="text-xs text-gray-300 mb-6 italic leading-relaxed">
                "{activeSlide.content}"
              </p>
              
              <ul className="space-y-3.5">
                {activeSlide.bulletPoints?.map((pt, idx) => (
                  <li key={idx} className="text-xs text-gray-300 flex items-start gap-2.5">
                    <span className="h-1.5 w-1.5 rounded-full bg-gold shrink-0 mt-1.5"></span>
                    <span>{pt}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Logo Watermark */}
            <div className="text-right text-[9px] text-gray-600 font-mono mt-8 uppercase tracking-widest">
              FoundrAI • Co-Founder Suite
            </div>
          </div>
        </div>
      )}

      {/* Hidden compilation area used when exporting PDF/Print */}
      <div id="print-area" className="hidden print:block text-black">
        <h1 className="text-2xl font-bold text-center mb-8 print-title uppercase tracking-widest border-b-2 border-black pb-3">
          {activeStartup?.name?.toUpperCase()} — Pitch Deck Outline
        </h1>
        {slides.map((s) => (
          <div key={s.slideNumber} className="slide-page p-6 border mb-4 bg-white rounded-md">
            <h2 className="text-lg font-bold print-title mb-2">
              Slide {s.slideNumber}: {s.title}
            </h2>
            <p className="text-xs italic mb-4 text-gray-700">"{s.content}"</p>
            <ul className="space-y-2 pl-4">
              {s.bulletPoints?.map((pt, idx) => (
                <li key={idx} className="text-xs list-disc pl-1">
                  {pt}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </div>
  );
};
