import React from 'react';
import { Shield, ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';

export const PrivacyPolicy: React.FC = () => {
  return (
    <div className="min-h-screen bg-black text-white px-6 py-12 md:py-20 max-w-4xl mx-auto selection:bg-gold/30">
      <Link to="/" className="inline-flex items-center gap-2 text-gray-500 hover:text-gold transition-colors text-sm mb-12 font-mono">
        <ArrowLeft className="h-4 w-4" /> Back to Home
      </Link>
      
      <div className="flex items-center gap-3 mb-8">
        <Shield className="h-8 w-8 text-gold" />
        <h1 className="text-3xl md:text-5xl font-bold tracking-tight">Privacy Policy</h1>
      </div>
      
      <div className="prose prose-invert prose-gold max-w-none text-gray-300 space-y-8 leading-relaxed">
        <p className="text-sm font-mono text-gray-500 uppercase tracking-widest border-b border-dark-border pb-4">
          Last Updated: {new Date().toLocaleDateString()}
        </p>
        
        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">1. Information We Collect</h2>
          <p>
            At FoundrAI, we collect information that you provide directly to us when setting up your virtual co-founder environment, including your name, email address, and the business data (startup names, descriptions, target markets) you input into our platform.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">2. How We Use Your Information</h2>
          <p>
            We use the information we collect to:
          </p>
          <ul className="list-disc pl-5 space-y-2 text-gray-400">
            <li>Generate personalized SWOT analyses, MVP roadmaps, and pitch decks using our specialized AI agents.</li>
            <li>Maintain and improve our platform security, routing, and service quality.</li>
            <li>Communicate with you regarding your account, updates, and platform changes.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">3. Data Security & AI Processing</h2>
          <p>
            Your startup ideas are securely transmitted to our AI processing cluster. We employ robust encryption protocols to ensure your intellectual property remains confidential. We do not claim ownership of any business models, strategies, or slide decks generated by the platform on your behalf.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">4. Contact Us</h2>
          <p>
            If you have any questions about this Privacy Policy or your data, please contact our data protection team at privacy@foundrai.com.
          </p>
        </section>
      </div>
      
      <div className="mt-20 text-center border-t border-dark-border pt-8">
        <p className="text-[10px] text-gray-600 font-mono uppercase tracking-widest">
          &copy; {new Date().getFullYear()} FoundrAI. All rights reserved.
        </p>
      </div>
    </div>
  );
};
