import React from 'react';
import { Scale, ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';

export const TermsConditions: React.FC = () => {
  return (
    <div className="min-h-screen bg-black text-white px-6 py-12 md:py-20 max-w-4xl mx-auto selection:bg-gold/30">
      <Link to="/" className="inline-flex items-center gap-2 text-gray-500 hover:text-gold transition-colors text-sm mb-12 font-mono">
        <ArrowLeft className="h-4 w-4" /> Back to Home
      </Link>
      
      <div className="flex items-center gap-3 mb-8">
        <Scale className="h-8 w-8 text-gold" />
        <h1 className="text-3xl md:text-5xl font-bold tracking-tight">Terms & Conditions</h1>
      </div>
      
      <div className="prose prose-invert prose-gold max-w-none text-gray-300 space-y-8 leading-relaxed">
        <p className="text-sm font-mono text-gray-500 uppercase tracking-widest border-b border-dark-border pb-4">
          Effective Date: {new Date().toLocaleDateString()}
        </p>
        
        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">1. Acceptance of Terms</h2>
          <p>
            By accessing or using the FoundrAI platform, you agree to be bound by these Terms & Conditions. If you do not agree to all of the terms and conditions, you may not access the platform.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">2. Platform Services</h2>
          <p>
            FoundrAI provides an AI-powered virtual co-founder platform. The output generated by our AI models (including market research, risk assessments, and product roadmaps) is provided "as is" without warranty of any kind. You are solely responsible for verifying the accuracy, compliance, and viability of any business strategies generated before making financial decisions.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">3. Intellectual Property</h2>
          <p>
            You retain all rights to the initial business ideas you input into FoundrAI. You also retain ownership of the final deliverables (Pitch Decks, Kanban Boards, Validation Reports) exported from your workspace. FoundrAI retains all rights to its underlying software, UI design, logic, and agent prompting architecture.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">4. User Conduct</h2>
          <p>
            You agree not to use the platform to generate illicit, harmful, or legally prohibited content. We reserve the right to terminate accounts that violate our usage policies, attempt to reverse-engineer our proprietary agents, or attempt to abuse the API usage system.
          </p>
        </section>
      </div>

      <div className="mt-20 text-center border-t border-dark-border pt-8">
        <p className="text-[10px] text-gray-600 font-mono uppercase tracking-widest">
          &copy; {new Date().getFullYear()} FoundrAI. All rights reserved.
        </p>
      </div>
    </div>
  );
};
